### ISSUE TITLE
Allow only certain user(s)

### ISSUE THREAD

**Issue by stevenroose** [tuxmouraille/syncthing_ynh#3]
Is it possibe to allow only a single user to access SyncThing? F.e. the admin user, or a user specified during installation.

**Comment by tuxmouraille** [comment]
I'm not sure but I think yes.
I will check how to do this.
If you know how to do, there is no problem to fork.

**Comment by stevenroose** [comment]
Great.

**Comment by tuxmouraille** [comment]
You can manage access from Yunohost admin panel. Now there is only user per default who can access.

This package, does not support multi-instances, then there is only one instance for all users.
