### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by DamienCassou** [tuxmouraille/syncthing_ynh#4]
I've just installed syncthing_ynh. Installation went fine but when I go to the `<domain>/syncthing/` URL, I get a 502 Bad Gateway.

**Comment by DamienCassou** [comment]
In the YunoHost admin interface, the `syncthing` service is inactive and there is no associated journal. Is it because of systemd? (I'm on jessie)

**Comment by tuxmouraille** [comment]
Hello,
This is because there is a bug in the package I haven't corrected.
For the service journal it is normal, now I have used a sysinit script, I have to port to systemd for Jessie. But I have no time for that.

I'll try to correct the install script for today.

**Comment by tuxmouraille** [comment]
Hello,
My server is also a Jessie on 64bits. I tried on a VM, I had no problem with 502.

Syncthing is launch on startup but I can't manage it with service or systemctl.

I will investigate.
