### ISSUE TITLE
Host check error

### ISSUE THREAD

**Issue by M5oul** [tuxmouraille/syncthing_ynh#6]
On the web page, I have this message `Host check error` and can't do more.

**Comment by tuxmouraille** [comment]
Hello,
Sorry, there a new security policy on Syncthing and I have to upgrade the configuration.
Replace in /etc/nginx/<your domain>.d/syncthing.conf 127.0.0.1 (or localhost) by your server IP on your LAN and:

sudo systemctl restart nginx.service

This workaround can fix this issue.

https://docs.syncthing.net/users/faq.html#why-do-i-get-host-check-error-in-the-gui-api

**Comment by tuxmouraille** [comment]
Hello,
I have just upgraded the package. Can you try an upgrade, please?
From command line: 

 `sudo yunohost app upgrade -u https://github.com/tuxmouraille/syncthing_ynh syncthing`

**Comment by M5oul** [comment]
Nice, it works fine.
Thanks.
