### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by icf20** [tuxmouraille/syncthing_ynh#8]
hola por alguna razón después de instalar esto en yunohost da un error 

`502 Bad Gateway`

`nginx`

si se instala manualmente con apt-get no hay problema alguno, si es instala manualmente por la interfaz de yunohost poniendo https://github.com/tuxmouraille/syncthing_ynh todo va bien

**Comment by tuxmouraille** [comment]
Hola,
No hablo español, uso Google translate.
Perdon no vi su mensaje.
Creo que el servicio syncthing no se ha iniciado.
Prueba a reiniciar el servicio syncthing desde la interfaz de administración de Yunohost o con el comando:

sudo restart systemctl syncthing.service
